config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :subreddits

end

app/models/subreddit.rb
class Subreddit < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
require 'net/http'

class HomeController < ApplicationController
  def index
  	#@subreddits = Subreddit.all.to_a
  	#url = URI.parse( 'http://metareddit.com/reddits/over18/list' )
  	#req = Net::HTTP::Get.new( url.to_s )
  	#res = Net::HTTP.start( url.host, url.port ) { |http| 
  	#	http.request( req )
  	#}

  	#@scrape = res.body
  end
end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  before_action :set_subreddit, only: [:show, :edit, :update, :destroy]

  # GET /subreddits
  # GET /subreddits.json
  def index
    @subreddits = Subreddit.all
  end

  # GET /subreddits/1
  # GET /subreddits/1.json
  def show
  end

  # GET /subreddits/new
  def new
    @subreddit = Subreddit.new
  end

  # GET /subreddits/1/edit
  def edit
  end

  # POST /subreddits
  # POST /subreddits.json
  def create
    @subreddit = Subreddit.new(subreddit_params)

    respond_to do |format|
      if @subreddit.save
        format.html { redirect_to @subreddit, notice: 'Subreddit was successfully created.' }
        format.json { render :show, status: :created, location: @subreddit }
      else
        format.html { render :new }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subreddits/1
  # PATCH/PUT /subreddits/1.json
  def update
    respond_to do |format|
      if @subreddit.update(subreddit_params)
        format.html { redirect_to @subreddit, notice: 'Subreddit was successfully updated.' }
        format.json { render :show, status: :ok, location: @subreddit }
      else
        format.html { render :edit }
        format.json { render json: @subreddit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subreddits/1
  # DELETE /subreddits/1.json
  def destroy
    @subreddit.destroy
    respond_to do |format|
      format.html { redirect_to subreddits_url, notice: 'Subreddit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subreddit
      @subreddit = Subreddit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subreddit_params
      params.require(:subreddit).permit(:link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/views/home/index.html.erb
<div id="content" style="height: 100%; overflow: scroll;"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="height: 100%;">
<head>
  <title>Reddit Viewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="height: 100%;">

<%= yield %>

</body>
</html>

app/views/subreddits/_form.html.erb
<%= form_for(@subreddit) do |f| %>
  <% if @subreddit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subreddit.errors.count, "error") %> prohibited this subreddit from being saved:</h2>

      <ul>
      <% @subreddit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subreddits/edit.html.erb
<h1>Editing subreddit</h1>

<%= render 'form' %>

<%= link_to 'Show', @subreddit %> |
<%= link_to 'Back', subreddits_path %>

app/views/subreddits/index.html.erb
<h1>Listing subreddits</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subreddits.each do |subreddit| %>
      <tr>
        <td><%= subreddit.link %></td>
        <td><%= link_to 'Show', subreddit %></td>
        <td><%= link_to 'Edit', edit_subreddit_path(subreddit) %></td>
        <td><%= link_to 'Destroy', subreddit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subreddit', new_subreddit_path %>

app/views/subreddits/new.html.erb
<h1>New subreddit</h1>

<%= render 'form' %>

<%= link_to 'Back', subreddits_path %>

app/views/subreddits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @subreddit.link %>
</p>

<%= link_to 'Edit', edit_subreddit_path(@subreddit) %> |
<%= link_to 'Back', subreddits_path %>